const paths={mail:'M3 5h18v14H3z M3 5l9 7 9-7',pin:'M12 22s7-8 7-14a7 7 0 0 0-14 0c0 6 7 14 7 14z M9.5 8a2.5 2.5 0 1 0 5 0 2.5 2.5 0 1 0-5 0',phone:'M5 3l4 4-2 3c2 3 4 5 7 6l3-2 4 4-2 3C10 21 3 14 3 5z',download:'M12 3v12m-5-5 5 5 5-5M4 15v6h16v-6',briefcase:'M3 7h18v14H3zM8 7V3h8v4M3 12h18M10 10v5h4v-5',database:'M21 5c0 2-4 4-9 4S3 7 3 5s4-4 9-4 9 2 9 4zM3 5v14c0 2 4 4 9 4s9-2 9-4V5M3 12c0 2 4 4 9 4s9-2 9-4',monitor:'M2 3h20v14H2zM12 17v5M7 22h10',server:'M3 2h18v8H3zM3 14h18v8H3zM6 6h1m3 0h1m-5 12h1m3 0h1',boxes:'M12 1l6 3v7l-6 3-6-3V4zM6 4l6 3 6-3M12 7v7M6 11l-5 3v7l6 3 5-3v-7M1 14l6 3 5-3M7 17v7M18 11l5 3v7l-6 3-5-3M12 14l5 3 6-3M17 17v7',graduation:'M1 8l11-6 11 6-11 6zM5 11v7c4 4 10 4 14 0v-7M23 8v12',globe:'M12 1a11 11 0 1 0 0 22 11 11 0 1 0 0-22M1 12h22M12 1c-7 7-7 15 0 22M12 1c7 7 7 15 0 22M3 6h18M3 18h18',code:'M8 5l-7 7 7 7m8-14 7 7-7 7M14 2l-4 20'};
function icon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.code}"/></svg>`}
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
const technologies=[['Python','Py','#ffd343'],['Flask','Fl','#f5f5f5'],['Laravel','L','#ff2d20'],['PHP','php','#a497ef'],['CodeIgniter','CI','#ff493a'],['APIs REST','code','#eee'],['MySQL','My','#46a9d1'],['MariaDB','M','#eeb7a1'],['PostgreSQL','Pg','#6da9d7'],['SQL Server','SQL','#ff133b'],['ETL','database','#bdafe7','con SQL/Python'],['Linux','Lx','#ffdc52'],['Apache / Nginx','N','#29cd58'],['VPS','server','#599cfa'],['Dominios y DNS','globe','#599cfa']];
document.getElementById('tech-grid').innerHTML=technologies.map(([name,symbol,color,note])=>`<div class="tech"><span class="tech-symbol" style="--tech-color:${color}">${paths[symbol]?icon(symbol):symbol}</span><span>${name}${note?`<small>${note}</small>`:''}</span></div>`).join('');
const techIcons=['python','flask','laravel','php','codeigniter',null,'mysql','mariadb','postgresql','microsoftsqlserver',null,'linux','nginx'];
document.querySelectorAll('.tech-symbol').forEach((el,index)=>{if(techIcons[index])el.innerHTML=`<img src="assets/${techIcons[index]}.svg" alt="" width="40" height="40" loading="lazy">`});
const toggle=document.querySelector('.menu-toggle'),nav=document.getElementById('main-nav');
function closeMenu(){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Abrir menú')}
toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú')});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
const links=[...nav.querySelectorAll('a')];const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting){const link=links.find(a=>a.hash==='#'+entry.target.id);if(link){links.forEach(a=>{a.classList.remove('active');a.removeAttribute('aria-current')});link.classList.add('active');link.setAttribute('aria-current','location')}}}},{rootMargin:'-15% 0px -65% 0px',threshold:0});document.querySelectorAll('main section[id]').forEach(s=>observer.observe(s));
const projects={web:{title:'Sistemas e información web',description:'En Clínica La Luz participé en el mantenimiento de un sistema PHP, la optimización de vistas y consultas SQL, y el desarrollo de módulos CRUD con Laravel e Inertia.js + Vue.js para pacientes, médicos y usuarios. En UPT FAEDCOH gestioné contenidos y verifiqué enlaces y secciones del portal institucional. En TARCC desarrollé recursos web responsivos para facilitar el acceso a información y servicios.'},automation:{title:'Formularios y seguimiento',description:'En TARCC implementé formularios con validaciones, lógica condicional y controles de calidad de datos; automaticé procesos y diseñé tableros de seguimiento en hojas de cálculo. En UTP automaticé y sistematicé información con matrices de control, formularios y tableros para la gestión académica y operativa.'},data:{title:'Consolidación y tableros',description:'Trabajo con procesos ETL en SQL y Python para transformar y consolidar información, además de optimizar consultas mediante indexación y tuning. En TARCC elaboré reportes, matrices y consolidados para apoyar la toma de decisiones. En la Escuela de Formación Artística administré bases de datos en Excel y Google Sheets, con validación y respaldos periódicos.'}};
const dialog=document.getElementById('project-dialog');dialog.setAttribute('aria-labelledby','dialog-title');document.querySelectorAll('[data-project]').forEach(button=>button.addEventListener('click',()=>{const p=projects[button.dataset.project];document.getElementById('dialog-title').textContent=p.title;document.getElementById('dialog-description').textContent=p.description;dialog.showModal();document.body.classList.add('dialog-open')}));dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>document.body.classList.remove('dialog-open'));document.getElementById('year').textContent=new Date().getFullYear();
